### ISSUE TITLE
Partikeleffekte ToDo

### ISSUE THREAD

**Issue by LRod1** [Gk1mtd/heimathafen#10]
- [x] Explosion (z.B. wenn eine Mine explodiert)
- [ ] Sonar-Ping (z.B. als sich ausbreitender grüner Ring um das U-Boot)
- [x] Funken (bei Kollision mit Felsen)
- [ ] Störkörper (abgefeuert aus dem Heck des U-Boots, um feindliche Torpedos abzuwehren)
- [x] Blasen hinter Torpedo und U-Boot
- [ ] Fliegerbomben beim Auftauchen
